# Generated by Django 5.0.2 on 2024-02-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('year', models.DateField()),
                ('img', models.ImageField(upload_to='gallery')),
                ('director', models.CharField(max_length=250)),
                ('producer', models.CharField(max_length=250)),
                ('cast', models.TextField()),
            ],
        ),
    ]
