# Generated by Django 5.0.2 on 2024-02-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displayapp', '0002_rename_img_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='img',
        ),
    ]
